# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.1.0
  orb-tools: circleci/orb-tools@9.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecs/deploy-service-update:
          aws-region: us-east-1
          family: AWS_DEFAULT_REGION
          cluster-name: 'arn:aws:ecs:us-east-1:316893886507:cluster/pvr'
          container-image-name-updates: "container=pvr-service,image-and-tag=316893886507.dkr.ecr.us-east-1.amazonaws.com/pvr:sql"
          verify-revision-is-deployed: true
